### ISSUE TITLE
Definir relaciones con otros vocabularios

### ISSUE THREAD

**Issue by paoespinozarias** [opencitydata/commons-direccion-postal#4]
Si bien en la definición del concepto _esdir:DireccionPostal_ se menciona que se pueden utilizar las propiedades definidas en los vocabularios de división administrativa española (_esadm_) y en el callejero (_escjr_) sería útil definir en el vocabulario la relación entre:
- _esdir:DireccionPostal_ y _escjr:Portal_, por ejemplo: _esdir:portalResidencia_
- _esdir:DireccionPostal_ y _escjr:Via_, por ejemplo: _esdir:viaResidencia_ ¿o se podría usar directamente _escjr:via_?
- _esdir:Direccion Postal_ y _escjr:TramoVia_, por ejemplo: esdir:numeracionResidencia ¿o bastaría con usar _escjr:tramoVia_?

Siguiendo esta definición de relaciones entre vocabularios, ¿estaría bien si se incluyen relaciones entre _esdir:DireccionPostal_ con los conceptos del vocabulario _esadm_? (por ejemplo:  _esdir:distritoResidencia_ para relacionar _esdir:DireccionPostal_ y _esadm:Distrito_). O a lo mejor, considerando que todos los conceptos del vocabulario _esadm_ son una especialización de _schema:Place_ ¿se podría pensar en incluir una relación más general en _esdir_ que pueda ser algo similar una inversa de _schema:address_?

**Comment by paoespinozarias** [comment]
¿Podría la nueva propiedad _portal_ (agregada al vocabulario de _Callejero_ para la solución de la [issue 16](https://github.com/opencitydata/urbanismo-infraestructuras-callejero/issues/16)) solucionar mi consulta acerca de cómo relacionar la _DireccionPostal_ con un _Portal_?

**Comment by ocorcho** [comment]
Sí, se pueden incluir todas estas propiedades en el vocabulario de callejero. ¿Puedes encargarte tú, @paoespinozarias ?

**Comment by ocorcho** [comment]
Entre otras mejoras, en el commit 7b9dd4c102535e72eccfa2cf64d7a9dc1665fa9f se han incluido varias relaciones entre DireccionPostal y clases de las ontologías de territorio (división administrativa de España) y callejero. Concretamente:
- escjr:via only escjr:Via (que a su vez podrá enlazarse con el tipo de vía si es necesario)
- escjr:tramo only escjr:Tramo (no se espera que se utilice mucho)
- escjr:portal only escjr:Portal  (no se espera que se utilice mucho)
- esadm:barrio only esadm:Barrio
- esadm:distrito only esadm:Distrito
- esadm:municipio only esadm:Municipio
